### ISSUE TITLE
Reserved Word Highlighting Ignores @

### ISSUE THREAD

**Issue by Calidus** [Microsoft/vscode-mssql#1065]
**Issue Type**
Bug

**Description**
`DECLARE @Counter INT;`

Counter will get highlighted like a reserved word.

This issue does not happen in SQL Operations Studio, so I don't think it is textmate issue.

**VS Code Info**
VS Code version: Code 1.20.1 (f88bbf9, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by kevcunnane** [comment]
@corivera any chance this class of issue was fixed in Ops Studio version of the grammar?

**Comment by abist** [comment]
@kevcunnane I believe it's fixed since I can't repro it on either the extension or on Ops Studio. @Calidus , can you please confirm whether this is fixed for you?

**Comment by Calidus** [comment]
I am still seeing the issue on  v1.3 of the extension that was released in December.

VSCode:
![image](https://user-images.githubusercontent.com/1683712/38253520-d989a160-3724-11e8-993a-bf37f094e568.png)

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:47:13.351Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

Ops Studio:
![image](https://user-images.githubusercontent.com/1683712/38253602-0f7d8408-3725-11e8-9694-9973c11eb99a.png)

Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by corivera** [comment]
@Calidus Syntax colorization works as expected for me on VSCode 1.21.1 with MSSQL 1.3. Do you still see this issue when changing the language mode for the document to SQL? (or even just saving it with the .sql file extension)
