### ISSUE TITLE
Cannot cancel long running Query.

### ISSUE THREAD

**Issue by nycgavin** [microsoft/vscode-mssql#18837]
- MSSQL Extension Version: 1.28.0
- VSCode Version: 1.97.2
- OS Version: Mac sonoma 14.5
- M1 chip
- MS Sql server 2019

Steps to Reproduce:

1. run this query on a new tab: Select * from ... join  [Linked Server] --this query runs for a long time
2. the query starts running, but the Query History says "No Queries Available" and the cancel button is hidden
3. The bottom of VS code says Executing Query. (P.S. if you click on the disconnect button at this point, the bottom says canceling query, but it will continue spinning for the next x minutes)
4. if you open another query tab and try to execute a different query, it opens a prompt and lets you choose the connection, but after you choose it, it just says testing profile on the bottom right corner but doesn't do anything.
5. When the first query finished executing (after 5 minutes, another error shows up that says: mssql: A query is already running for this editor session. Please cancel this query or wait for its completion.)

**Comment by nycgavin** [comment]
This extension is full of bugs, and I don't understand why Microsoft wants to retire Azure Data Studio, this is so bad.

**Comment by match-gabeflores** [comment]
I've also started to encounter this occasionally. I have to restart VSCode as a solution

**Comment by match-gabeflores** [comment]
hi @cssuh 

I don't know exactly when this occurs - it seems sporadic. I had a large result set and I'm not sure if it was still populating when i think i cancelled it (not sure here). the query successfully cancelled but it says "executing query" erroneously. 

1. What happens is the status bar will say "`Executing query`" forever and there's no Cancel button visible. 
![Image](https://github.com/user-attachments/assets/5bcde98c-d15d-4dee-b4ef-c94525c05a2e)

2. if i do the keyboard shortcut for cancel query, status bar says "`cancelling query`" forever.


![Image](https://github.com/user-attachments/assets/d2c5cd99-23da-4264-b526-ac2e5f237a6e)

When I actually look at what's going on in the server, the query isn't actually running. 

so it's left in a state where it says it's executing query or cancelling query forever and I can't run a new query. Worse, if open a new query window, it doesn't even connect to the server (just says `connecting `forever). 

On latest version of mssql on Cursor IDE (but don't think this is a cursor issue)

**Comment by match-gabeflores** [comment]
Related bug from 2022. they also mention restarting is the main solution. They're on VPN. I'm also always on VPN. Not sure if that helps. 
https://github.com/microsoft/vscode-mssql/issues/17433

**Comment by laurenastrid1** [comment]
fixed in https://github.com/microsoft/vscode-mssql/pull/19129

**Comment by AMurtagh** [comment]
@laurenastrid1 this is still occurring for me, despite running 1.31.0 from a couple of days ago. Can we re-open this and can I be of any further help in terms of diagnosis?

**Comment by cssuh** [comment]
hi @AMurtagh, do you have more data points you can share that might be helpful for reproducing the error?

**Comment by AMurtagh** [comment]
Hi folks,

Here I may need some help to know what's possible in terms of trace log collection. The symptom is the same to me but I can't put my hand on heart and say that the cause is the same!

I have one specific SQL server I operate against (It's a SQL Server clustered install running on a vendor's AWS EC2 instance). Every other server I operate against works fine, but this specific server deadlocks mid-query about 50% of the time on average, I can't cancel it and I have to restart VScode to run the query again which seems to resolve the issue. The same issue occurs on two devices of mine, and also for a colleague of mine operating against the same servers.

We have only been given read only credentials against the destination server in question, there is no VPN between us and it; just connection over WAN against an IP with an IP ACL.

If there's any extra info I can give you in terms of trace ouputs, logs, etc. that might help please let me know.

That said, the extension has also updated to 1.31.1 so hopefully I haven't (sod's law!) asked for this to be reopened and then having had it for months I'll never see it again lol

**Comment by cssuh** [comment]
@AMurtagh Can you set this setting to verbose so we can capture all the logs? 

![Image](https://github.com/user-attachments/assets/4549de13-e371-4c61-8243-10004053ddcf)
Then, if it occurs again, you can grab the logs.

You can then find the STS logs by going to:
Command Palette -> Developer: Open Extension Logs Folder 
open ms-mssql.mssql folder
sqltools.log

**Comment by sggoose** [comment]
Could we get an update on this? I see the pull request to close but this keeps getting pushed to further milestones?

**Comment by dbersan** [comment]
> Hi [@nycgavin](https://github.com/nycgavin) & [@match-gabeflores](https://github.com/match-gabeflores) just to clarify, I have two questions:
> 
> 1. Are you saying the cancel button (seen in screenshot below) is hidden while the query is still running?

I cannot see this button

> 2. Do you see the cancel button right after starting the query execution, and it disappears later on, or is it never there in the first place?
> 
> ![Image](https://github.com/user-attachments/assets/3d5b054a-5ce1-46cd-bbff-0ce72a1b8676)

Cannot see the button 

All I see is this loading floating box:

<img width="470" height="107" alt="Image" src="https://github.com/user-attachments/assets/ba4b589f-a681-47ad-ab02-c3657cedbf27" />

It stays there for like 5 minutes straight. There is literally no way to remove it, unless I disable the extension's notifications. 

I am also on VPN

**Comment by kburtram** [comment]
> > Hi [@nycgavin](https://github.com/nycgavin) & [@match-gabeflores](https://github.com/match-gabeflores) just to clarify, I have two questions:
> > 
> > 1. Are you saying the cancel button (seen in screenshot below) is hidden while the query is still running?
> 
> I cannot see this button
> 
> > 2. Do you see the cancel button right after starting the query execution, and it disappears later on, or is it never there in the first place?
> > 
> > ![Image](https://github.com/user-attachments/assets/3d5b054a-5ce1-46cd-bbff-0ce72a1b8676)
> 
> Cannot see the button
> 
> All I see is this loading floating box:
> 
> <img alt="Image" width="470" height="107" src="https://private-user-images.githubusercontent.com/25873377/495262418-ba4b589f-a681-47ad-ab02-c3657cedbf27.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkyODU2OTgsIm5iZiI6MTc1OTI4NTM5OCwicGF0aCI6Ii8yNTg3MzM3Ny80OTUyNjI0MTgtYmE0YjU4OWYtYTY4MS00N2FkLWFiMDItYzM2NTdjZWRiZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDAxVDAyMjMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDI5OTY3NzhmNjYyMDI2Yjg3Y2QyZjgyZWVlOTZhMzA4MmJhNzNkOTZkZmRlMjViMTUxNzAzNDI5MWFmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._K1y3odGpvcVAGxdc2v2WLPExClg0lhXUOX_rvMljrM">
> It stays there for like 5 minutes straight. There is literally no way to remove it, unless I disable the extension's notifications.
> 
> I am also on VPN

This looks like a hang during SELECT 1000 or other scripting operation - prior to query execution.  This is a different scenario than reporting in the original bug.  We should add a cancel button to the notification to allow aborting that operation, if it hangs for some reason.  Though we should probably track that in a different issue.

**Comment by aasimkhan30** [comment]
We have made a few fixes in this area. This includes 

1. Fixing query event listeners. 
https://github.com/microsoft/vscode-mssql/pull/20194
https://github.com/microsoft/vscode-mssql/pull/20216
https://github.com/microsoft/vscode-mssql/pull/20007
2. Fixing the state of toolbar icons 
https://github.com/microsoft/vscode-mssql/pull/20196
https://github.com/microsoft/vscode-mssql/pull/20026
https://github.com/microsoft/vscode-mssql/pull/20145
3. Resultset streaming
https://github.com/microsoft/vscode-mssql/pull/20034
4. Parallel message processing
https://github.com/microsoft/vscode-mssql/pull/20095

Closing this for now. The fixes will be all released in November 2025 release. Please open a new issue if there are queries are still hanging.
