### ISSUE TITLE
Continuous Authentication Requests When Connecting to Azure SQL Server Managed Instance Using MS Entra ID (MFA)

### ISSUE THREAD

**Issue by FranBestinver** [microsoft/vscode-mssql#19017]
- MSSQL Extension Version: 1.29.1
- VSCode Version: 
    1.98.2 (user setup)
    Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
    Date: 2025-03-12T13:32:45.399Z
    Electron: 34.2.0
    ElectronBuildId: 11161602
    Chromium: 132.0.6834.196
    Node.js: 20.18.2
    V8: 13.2.152.36-electron.0
    - OS Version: Windows_NT x64 10.0.22631

-------------------------------------------------------------

Hi, vscode-mssql team,

In our company, we have several databases in the Azure cloud that use Microsoft Entra ID (MFA) to authenticate users and connect. When I establish a connection to the server or one of the databases, I authenticate. However, each time I create a new tab and connect again to the DB, the authentication is requested repeatedly. I tried several solutions, using pooling options and establishing connections to the server, but the authentication is continuously requested, making working against an Azure server very tedious.

On the contrary, when you authenticate from SSMS, the authentication process is requested only once and is used against all connections to any database.

Is it possible to replicate this behavior in the vscode-mssql extension? Can we avoid the continuous authentications' loop?

Thanks in advanced.

Regards.

**Comment by keen85** [comment]
We are facing the same problem.

**Comment by keen85** [comment]
@Benjin, is there any hope for a fix?

**Comment by FranBestinver** [comment]
@keen85 , @Benjin .

It is solved in version 1.32.00 of the extension, isn't it?

**Comment by keen85** [comment]
@FranBestinver, I updated the extension to 1.32.00.
Unfortunately the behavior (constant requests to re-authenticate) is still the same for me; issue is not fixed.
Business users in our org already complain a lot that working with VS Code is much worse than Azure Data Studio (which is deprecated by Microsoft and we ask them not to use any more) 😖

**Comment by Benjin** [comment]
We've addressed some other instances of multiple auth prompts, but we haven't tracked down a repro for this one yet.

* If you set `"mssql.tracingLevel": "Verbose"`, is there anything that stands out in the logs related to Entra auth or tokens?
* If you sign out of all Entra accounts (using `MS SQL: Remove Microsoft Entra Account`) then clear the token cache (`MS SQL: Clear Microsoft Entra account token cache`), does this continue to happen?
* Does your connection involve a proxy, VPN, or sovereign/government cloud?

**Comment by FranBestinver** [comment]
For our team's connections the problem seem solved. Continuous Auth Requests are over. The only remaining minor error is this message on every first connections.

_"mssql: Error: TypeError: Cannot read properties of undefined (reading 'find')"_

Thanks to Extension team.

**Comment by keen85** [comment]
@Benjin `MS SQL: Remove Microsoft Entra Account` did the trick for me. Now it seems to work fine, thanks a lot!
