### ISSUE TITLE
Schema Compare:  Switch direction is disabled if both source and target are not currently populated

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/vscode-mssql#19335]
Steps to Reproduce:

1. Open schema compare from vscode
2. Note that the current project is defaulted to source and that until you enter a target the switch direction is disabled

This behavior is different than current ADS, ads you can switch comparison direction with only one side.

**Comment by jasonhorner** [comment]
hey @tauseefsiddique10  @lewis-sanchez  has this shipped? in the latest build it is still an issue

<img width="2376" height="1428" alt="Image" src="https://github.com/user-attachments/assets/4d38ad14-2b87-4b4f-b4aa-d2e1fa55a0d7" />

the switch is only active after adding a target

Not sure if this regressed or what happened thanks

**Comment by lewis-sanchez** [comment]
Hi @jasonhorner, looks like this was fixed in the July release and then a regression was introduced in August when telemetry was added to the controller logic.

**Comment by jasonhorner** [comment]
@lewis-sanchez  it looks as of the latest release is still doesn't work as expected. can we re-open this?

**Comment by lewis-sanchez** [comment]
Hi @jasonhorner, the January 2026 release is scheduled for early next week and it should be fixed in that release.
