### ISSUE TITLE
Results grid resets scroll location and selection when resizing a column

### ISSUE THREAD

**Issue by ransagy** [Microsoft/vscode-mssql#622]
- MSSQL Extension Version: 0.2.0 alpha 18 (with fix #604)
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open an SQL file or create a new one.
2. Connect to a DB and run any query that would have enough results to scroll.
3. Scroll down and select anything.
4. Resize a column.

Expected:
The column is resized and current scroll position and cell selection remains intact.

Actual:
The resized column is now selected entirely and the scroll position resets to the top.

**Comment by kburtram** [comment]
@coquagli I think this is the same behavior described in this issue https://github.com/Microsoft/vscode-mssql/issues/198

**Comment by coquagli** [comment]
Fixed with #646.

**Comment by ransagy** [comment]
Tried this with mssql alpha 23 from the releases page (and changed the config.js to take sqltoolsservice alpha 22 instead of 18), This still happens every other time i resize the column.

maybe its because of my frankenbuild, not sure.

Right now, I can select a single cell, resize, it will not change the selection or scroll back. Do it again, it still doesn't scroll but it now selects the entire column.

**Comment by coquagli** [comment]
Hey, thanks for following-up with this. I replicated your setups with a build from source and an install via .vsix, but was unable to reproduce the issue. Are you sure you grabbed the [correct alpha build](https://github.com/Microsoft/vscode-mssql/releases/tag/v0.2.0-alpha.23)?

**Comment by ransagy** [comment]
Just grabbed a fresh install of VSCode 1.8.1 and the generic vsix from that page. It installed sqltoolservice alpha 18.
I get the same result, selected 50 rows from a table, scrolled down a bit, choose a cell at random and resized its column's header. If i keep selecting a cell and resizing that column, i get varying results regarding selection - sometimes it changes, sometimes it does not. It does not lose scroll position though.

**Comment by coquagli** [comment]
Ahh, I see. I'll take another look at why that's happening.

**Comment by coquagli** [comment]
This got auto-closed when merging the change. Did the change fix your issues, @ransagy?

**Comment by ransagy** [comment]
This isn't available in any release atm, right? Only if i build from the dev branch. If so, I don't have an env set up right now, I'll see what i can do.

**Comment by coquagli** [comment]
Correct. As such, there's no rush. Feel free to wait for the next release if you need.

**Comment by ransagy** [comment]
@coquagli confirmed fixed in 0.3.0 alpha 1.

There is a slight issue that double clicking the border between headers to auto expand the column resets selection (probably due to that single clicking the header selects all that column) but that should probably be a opened under a different issue.
